# ในการเริ่มต้นใช้งานการอัพเดตเวอร์ชันของ Dependabot คุณจะต้องระบุว่า
# ระบบนิเวศของแพ็คเกจเพื่ออัปเดตและตำแหน่งของแพ็คเกจ
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      ช่วงเวลา: "รายวัน"
<a class="/s2Q0d" href="#" aria-label="Paấuðn" role="menuitem"jsaction="Kcbrbe"

data-ved="OahUKEwjitPWXnlfxAhWKT30KH TraAloQnJCCCAM"></a>

<a class="rYDfvb" href="/?hl=th&sa=X&ved=0ahUKEwjitPWXnIfxAhWKT30KHTraAloqnZcCCAQ"

role="menuitem"><img class="EuAkLc" src="https://www.gstatic.com/navigationdrawer/home_icon.svg" alt="">ůr

แรก</a>

<a class="rYDfvb" href="https://myactivity.google.com/product/search?utm_source=google&hl=th&sa

=X&ved=0ahUKEwjitPWXnlfxAhWKT30KHTraAloQsLSECAU" role="menuitem"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/search_activity_icon.svg" alt="">ห้องซาวน่า usršân</a>

<a class="rYDfvb" href="/save?hl=th&sa=X&ved=0ahUKEwjitPWXnIfxAhWKT30KHTraAloQnpcCCAY"

บทบาท="menuitem"><img class="EuAkLc" src="https://www.gstatic.com/navigationdrawer/save_icon.svg"

alt="">คอลเล็กชัน</a>

<a class="rYDfvb" href="/search/managesearches?

sa=X&ved=0ahUKEwjitPWXnlfxAhWKT30KHTraAloQ340DCAC" role="menuitem"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/manage_searches_icon.png" alt="">75funui ชาม</a>

<a class="rYDfvb" href="/preferences?

hl=th&sa=X&ved=0ahUKEwjitPWXnlfxAhWKT30KHTraAloQn5cCCAg" role="menuitem"><img

class="EuAkLc" src="https://www.gstatic.com/navigationdrawer/settings_icon.svg" alt="">750 </a>

<a class="rYDfvb" href="https://myactivity.google.com/privacyadvisor/search?utm_source=googlemenu&sa

=X&ved=0ahUKEwjitPWXnlfxAhWKT3OKHTraAloQp9gDCAk" role="menuitem"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/privacy_advisor_icon.svg" alt="">ค้นหา VoWavjąulu</a>

<a class="rYDfvb" href="/safesearch?hl=th&prev=https://www.google.com/?gws_rd%3Dssl&sa

=X&ved=0ahUKEwjitPWXnIfxAhWKT3OKHRaAloQkqkxCAo" role="menuitem"><img class="EUAKLc"

src="https://www.gstatic.com/navigationdrawer/explicit_icon.svg" alt="">Bouwannspiunonitúan lainnya:

ปิด</a>

<a class="rYDfvb" href="https://google.com/search/howsearchworks/" role="menuitem"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/how_search_works_icon.svg" alt="">jšansvintuvos ค้นหา</a>

<a class="rYDfvb" href="https://support.google.com/websearch/?p=Ws_results_help&hl=th" role="menuitem"

ping="/url?sa=t&rct=j&source=webhp&url=https://support.google.com/websearch/%3Fp

%3Dws_results_help%26hl%3Dth&amp;ved=0ahUKEwjitPWXnIfxAhWKT30KH TraAloQoJCCCAs&amp;usg

=AOvVaw2MICUIMSYu3IXwsCqZ8ijl" oncontextmenu="google.ctpacw.cm(this)"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/help_icon.svg" alt="">A114Diuinão</a>

<a class="rYDfvb" href="#" data-bucket="mobilehp" data-psd-twd="dl" role="menuitem" target="_blank"

jsaction="feqbab" data-ved="0ahUKEwjitPWXnIfxAhWKT30KHTraAloQrsICCAw"><img class="EuAkLc"

src="https://www.gstatic.com/navigationdrawer/feedback_icon.svg" alt=">JAITHÂniðu</a>

<a class="active">rinna</a>

<a href="https://www.google.com/webhp?output=search&amp;tbm=isch&amp;tbo=u&amp;sa=X&amp;ved=

0ahUKEwjitPWXnIfxAhWKT30KHTraAlOQOtQDCA80AQ">w</a>
